services:
  vert:
    container_name: vert
    image: VERT-sh/vert:latest # will build under this name
    build:
      context: .
      args:
        PUB_HOSTNAME: "vert.sh"
        PUB_PLAUSIBLE_URL: "https://plausible.example.com"
        PUB_ENV: "production"
    restart: unless-stopped
    ports:
      - 3000:80