services:
  vert:
    container_name: vert
    image: gchr.io/vert-sh/vert:latest
    restart: unless-stopped
    build:
      context: .
      args:
        PUB_HOSTNAME: ${PUB_HOSTNAME:-vert.sh}
        PUB_PLAUSIBLE_URL: ${PUB_PLAUSIBLE_URL:-}
        PUB_ENV: ${PUB_ENV:-production}
        PUB_VERTD_URL: ${PUB_VERTD_URL:-https://vertd.vert.sh}
    ports:
      - ${PORT:-3000}:80
